files:
  - source: /src/main/resources/assets/createcasing/lang/en_us.json
    translation: /src/main/resources/assets/createcasing/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        ja: ja_jp
        ko: ko_kr
        ru: ru_ru
bundles:
  - 1
