org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21,)
neo_version=21.1.129
neo_version_range=[21,)
loader_version_range=[2,)

## Mod Properties
mod_id=createcasing
mod_name=Create Encased
mod_license=MIT
mod_version=1.7.1-fix1
mod_group_id=fr.iglee42
mod_authors=iglee42
mod_description=Encase Your World !

jei_version=19.21.1.300
rei_version=18.0.800
cloth_config_version=11.1.106
architectury_version=9.1.12

create_version = 6.0.3-46
create_version_range = [6.0.3,)
ponder_version = 1.0.45
flywheel_version = 1.0.1
registrate_version = MC1.21-1.3.0+62